### ISSUE TITLE
TableConverter with Java 8 Lambdas: "Not a Map or List" exception is incorrect and not helpful

### ISSUE THREAD

**Issue by bencody** [cucumber/cucumber-jvm#936]
I'm using cucumber-core-1.2.4 and cucumber-java8-1.2.4. TableConverter.java throws the following exception when a Java 8 Lambda Given/When/Then is used with a List argument.

```
Scenario: Test
Given the list of strings
| a |
| b |
| c |
```

```
Given("the list of strings", (List<String> strings) -> {
  // do something
});
```

```
cucumber.runtime.CucumberException: Not a Map or List type: interface java.util.List
    at cucumber.runtime.table.TableConverter.convert(TableConverter.java:75)
    at cucumber.runtime.StepDefinitionMatch.tableArgument(StepDefinitionMatch.java:97)
    at cucumber.runtime.StepDefinitionMatch.transformedArgs(StepDefinitionMatch.java:74)
    at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
...
```

Work-arounds:

Use DataTable as an argument type and manually convert it to a List:

```
Given("the list of strings", (DataTable stringsDataTable) -> {
  List<String> strings = stringsDataTable.asList(String.class);
  // do something
});
```

Or use the more verbose classic syntax:

```
@Given("the list of strings")
public void the_list_of_strings(List<String> strings) {
  // do something
};
```

If it's impossible to determine the type of the lambda list argument, then the exception message should be changed to something like "Type of List or Map argument could not be determined. If you're using Java 8 lambdas, use DataTable arguments instead and manually convert them to a List or Map with the asList/asMap methods". Or if you think that's too verbose for an exception, add that information to the JavaDocs of the TableConverter class.

**Comment by RichardBradley** [comment]
> If it's impossible to determine the type of the lambda list argument,

This is impossible with the current design, yes.
The current lambda steps parser uses reflection on the lambda object to get the param types, but the List generic type param info isn't retained at runtime.

The exception message has been fixed on master: https://github.com/cucumber/cucumber-jvm/commit/88ad3bd6506fab9efadd1be389b1554782009e22

I'm looking into support for this in #937 

For the record, here's a full javap class dump of a step like the example above:

```
Classfile /C:/Work/cucumber-jvm/java8/proxyClasses/cucumber/runtime/java8/test/LambdaStepdefs$$Lambda$1.class
  Last modified 01-Dec-2015; size 390 bytes
  MD5 checksum 95e4e84eb884d3f8d705a26c71dbf2cf
final class cucumber.runtime.java8.test.LambdaStepdefs$$Lambda$1 implements cucumber.api.java8.StepdefBody$A1
  minor version: 0
  major version: 52
  flags: ACC_FINAL, ACC_SUPER, ACC_SYNTHETIC
Constant pool:
   #1 = Utf8               cucumber/runtime/java8/test/LambdaStepdefs$$Lambda$1
   #2 = Class              #1             // cucumber/runtime/java8/test/LambdaStepdefs$$Lambda$1
   #3 = Utf8               java/lang/Object
   #4 = Class              #3             // java/lang/Object
   #5 = Utf8               cucumber/api/java8/StepdefBody$A1
   #6 = Class              #5             // cucumber/api/java8/StepdefBody$A1
   #7 = Utf8               <init>
   #8 = Utf8               ()V
   #9 = NameAndType        #7:#8          // "<init>":()V
  #10 = Methodref          #4.#9          // java/lang/Object."<init>":()V
  #11 = Utf8               accept
  #12 = Utf8               (Ljava/lang/Object;)V
  #13 = Utf8               java/util/List
  #14 = Class              #13            // java/util/List
  #15 = Utf8               cucumber/runtime/java8/test/LambdaStepdefs
  #16 = Class              #15            // cucumber/runtime/java8/test/LambdaStepdefs
  #17 = Utf8               lambda$new$0
  #18 = Utf8               (Ljava/util/List;)V
  #19 = NameAndType        #17:#18        // lambda$new$0:(Ljava/util/List;)V
  #20 = Methodref          #16.#19        // cucumber/runtime/java8/test/LambdaStepdefs.lambda$new$0:(Ljava/util/List;)V
  #21 = Utf8               Code
{
  public void accept(java.lang.Object);
    descriptor: (Ljava/lang/Object;)V
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=2, args_size=2
         0: aload_1
         1: checkcast     #14                 // class java/util/List
         4: invokestatic  #20                 // Method cucumber/runtime/java8/test/LambdaStepdefs.lambda$new$0:(Ljava/util/List;)V
         7: return
}
```

note that the "list" type param has been erased at this point (const \#20).

Here's the containing class, which has the lambda body as a statric method (in this version of the JVM, but that's an implementation detail that may not be reliable):

```
Classfile /C:/Work/cucumber-jvm/java8/target/test-classes/cucumber/runtime/java8/test/LambdaStepdefs.class
  Last modified 01-Dec-2015; size 1631 bytes
  MD5 checksum a3687795c039397a024fdfa4dffc95df
  Compiled from "LambdaStepdefs.java"
public class cucumber.runtime.java8.test.LambdaStepdefs implements cucumber.api.java8.En
  minor version: 0
  major version: 52
  flags: ACC_PUBLIC, ACC_SUPER
Constant pool:
   #1 = Methodref          #9.#32         // java/lang/Object."<init>":()V
   #2 = Methodref          #33.#34        // java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
   #3 = String             #35            // the list of strings
   #4 = InvokeDynamic      #0:#41         // #0:accept:()Lcucumber/api/java8/StepdefBody$A1;
   #5 = Methodref          #8.#42         // cucumber/runtime/java8/test/LambdaStepdefs.Given:(Ljava/lang/String;Lcucumber/api/java8/StepdefBody$A1;)V
   #6 = Fieldref           #43.#44        // java/lang/System.out:Ljava/io/PrintStream;
   #7 = Methodref          #45.#46        // java/io/PrintStream.println:(Ljava/lang/Object;)V
   #8 = Class              #47            // cucumber/runtime/java8/test/LambdaStepdefs
   #9 = Class              #48            // java/lang/Object
  #10 = Class              #49            // cucumber/api/java8/En
  #11 = Class              #50            // cucumber/runtime/java8/test/LambdaStepdefs$Person
  #12 = Utf8               Person
  #13 = Utf8               InnerClasses
  #14 = Utf8               lastInstance
  #15 = Utf8               Lcucumber/runtime/java8/test/LambdaStepdefs;
  #16 = Utf8               <init>
  #17 = Utf8               ()V
  #18 = Utf8               Code
  #19 = Utf8               LineNumberTable
  #20 = Utf8               LocalVariableTable
  #21 = Utf8               this
  #22 = Utf8               alreadyHadThisManyCukes
  #23 = Utf8               Ljava/lang/Integer;
  #24 = Utf8               lambda$new$0
  #25 = Utf8               (Ljava/util/List;)V
  #26 = Utf8               strings
  #27 = Utf8               Ljava/util/List;
  #28 = Utf8               SourceFile
  #29 = Utf8               LambdaStepdefs.java
  #30 = Utf8               RuntimeInvisibleAnnotations
  #31 = Utf8               Lcucumber/AnnotProc;
  #32 = NameAndType        #16:#17        // "<init>":()V
  #33 = Class              #51            // java/lang/Integer
  #34 = NameAndType        #52:#53        // valueOf:(I)Ljava/lang/Integer;
  #35 = Utf8               the list of strings
  #36 = Utf8               BootstrapMethods
  #37 = MethodHandle       #6:#54         // invokestatic java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
  #38 = MethodType         #55            //  (Ljava/lang/Object;)V
  #39 = MethodHandle       #6:#56         // invokestatic cucumber/runtime/java8/test/LambdaStepdefs.lambda$new$0:(Ljava/util/List;)V
  #40 = MethodType         #25            //  (Ljava/util/List;)V
  #41 = NameAndType        #57:#60        // accept:()Lcucumber/api/java8/StepdefBody$A1;
  #42 = NameAndType        #61:#62        // Given:(Ljava/lang/String;Lcucumber/api/java8/StepdefBody$A1;)V
  #43 = Class              #63            // java/lang/System
  #44 = NameAndType        #64:#65        // out:Ljava/io/PrintStream;
  #45 = Class              #66            // java/io/PrintStream
  #46 = NameAndType        #67:#55        // println:(Ljava/lang/Object;)V
  #47 = Utf8               cucumber/runtime/java8/test/LambdaStepdefs
  #48 = Utf8               java/lang/Object
  #49 = Utf8               cucumber/api/java8/En
  #50 = Utf8               cucumber/runtime/java8/test/LambdaStepdefs$Person
  #51 = Utf8               java/lang/Integer
  #52 = Utf8               valueOf
  #53 = Utf8               (I)Ljava/lang/Integer;
  #54 = Methodref          #68.#69        // java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
  #55 = Utf8               (Ljava/lang/Object;)V
  #56 = Methodref          #8.#70         // cucumber/runtime/java8/test/LambdaStepdefs.lambda$new$0:(Ljava/util/List;)V
  #57 = Utf8               accept
  #58 = Class              #72            // cucumber/api/java8/StepdefBody$A1
  #59 = Utf8               A1
  #60 = Utf8               ()Lcucumber/api/java8/StepdefBody$A1;
  #61 = Utf8               Given
  #62 = Utf8               (Ljava/lang/String;Lcucumber/api/java8/StepdefBody$A1;)V
  #63 = Utf8               java/lang/System
  #64 = Utf8               out
  #65 = Utf8               Ljava/io/PrintStream;
  #66 = Utf8               java/io/PrintStream
  #67 = Utf8               println
  #68 = Class              #73            // java/lang/invoke/LambdaMetafactory
  #69 = NameAndType        #74:#77        // metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
  #70 = NameAndType        #24:#25        // lambda$new$0:(Ljava/util/List;)V
  #71 = Class              #78            // cucumber/api/java8/StepdefBody
  #72 = Utf8               cucumber/api/java8/StepdefBody$A1
  #73 = Utf8               java/lang/invoke/LambdaMetafactory
  #74 = Utf8               metafactory
  #75 = Class              #80            // java/lang/invoke/MethodHandles$Lookup
  #76 = Utf8               Lookup
  #77 = Utf8               (Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
  #78 = Utf8               cucumber/api/java8/StepdefBody
  #79 = Class              #81            // java/lang/invoke/MethodHandles
  #80 = Utf8               java/lang/invoke/MethodHandles$Lookup
  #81 = Utf8               java/lang/invoke/MethodHandles
{
  public cucumber.runtime.java8.test.LambdaStepdefs();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=3, locals=2, args_size=1
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: iconst_1
         5: invokestatic  #2                  // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
         8: astore_1
         9: aload_0
        10: ldc           #3                  // String the list of strings
        12: invokedynamic #4,  0              // InvokeDynamic #0:accept:()Lcucumber/api/java8/StepdefBody$A1;
        17: invokevirtual #5                  // Method Given:(Ljava/lang/String;Lcucumber/api/java8/StepdefBody$A1;)V
        20: return
      LineNumberTable:
        line 21: 0
        line 32: 4
        line 44: 9
        line 58: 20
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      21     0  this   Lcucumber/runtime/java8/test/LambdaStepdefs;
            9      12     1 alreadyHadThisManyCukes   Ljava/lang/Integer;
}
SourceFile: "LambdaStepdefs.java"
RuntimeInvisibleAnnotations:
  0: #31()
InnerClasses:
     public static #12= #11 of #8; //Person=class cucumber/runtime/java8/test/LambdaStepdefs$Person of class cucumber/runtime/java8/test/LambdaStepdefs
     public static #59= #58 of #71; //A1=class cucumber/api/java8/StepdefBody$A1 of class cucumber/api/java8/StepdefBody
     public static final #76= #75 of #79; //Lookup=class java/lang/invoke/MethodHandles$Lookup of class java/lang/invoke/MethodHandles
BootstrapMethods:
  0: #37 invokestatic java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
    Method arguments:
      #38 (Ljava/lang/Object;)V
      #39 invokestatic cucumber/runtime/java8/test/LambdaStepdefs.lambda$new$0:(Ljava/util/List;)V
      #40 (Ljava/util/List;)V

```

here the list param type can be seen in const \#40, again the String has been erased at runtime.

This is different to the declared method case, where all type params are retained for reflection using `getGenericParameterTypes`
